---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gb-rm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gb-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gb-app
    spec:
      containers:
        - image: redmine:4.1.1
          name: redmine
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 300m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 400Mi
          env:
            - name: REDMINE_DB_POSTGRES
              value: gb-pg-service
            - name: REDMINE_DB_USERNAME
              value: testuser
            - name: REDMINE_DB_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: REDMINE_DB_DATABASE
              value: testdatabase
            - name: REDMINE_SECRET_KEY_BASE 
              valueFrom:
                secretKeyRef:
                  name: redmine-secret
                  key: REDMINE_SECRET_KEY_BASE


