---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gb-4-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gb-4-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gb-4-app
    spec:
      containers:
        - image: postgres:10.13
          name: postgres
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 300m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 400Mi
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_USER
              value: testuser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: testdatabase
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: db-pvc

